@startuml

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml

@startuml
package auth{
    class User{
    Integer id
    String username
    String password
    String opendId
    }
}

package account{

    class Ledger{
    Integer id
    Integer userId
    String ledgerName
    BigDecimal totalIncome
    BigDecimal totalExpense
    List<Journal> journalList
    }

    abstract class Warehouse{
    Integer id
    String warehouseName
    Double balance
    Integer userId
    }

    class Currency{
    Integer id
    String code
    String name
    }

    abstract class Journal{
    Integer id
    Integer warehouseId
    Integer ledgerId
    Double amount
    Timestamp createTime
    }

    class JournalType{
    typeName
    }

    class InvestmentWarehouse
    class VaultWarehouse

    Journal *-- JournalType
    Journal *-- Currency

    Ledger o-- Journal
    Warehouse o-- Journal

    Warehouse <|-- InvestmentWarehouse
    Warehouse <|-- VaultWarehouse

    User o-- Ledger
    User o-- Warehouse

}

@enduml

@startuml
class 账簿

class 金库

abstract class 收支流水项

class 收入记录

class 支出记录

账簿 <-- 金库

金库 <-- 收支流水项

收支流水项 <|-- 收入记录

收支流水项 <|-- 支出记录



@enduml